### ISSUE TITLE
⚙ Initial Set up

### ISSUE THREAD

**Issue by dgd03146** [dgd03146/about#1]
## Description
Initial Set up for the project

## To-do
- [x] Set up ts.config
- [x] Set up Eslint
- [x] Set up Husky
- [x] Set up Prettier
- [x] Set up Next.js
- [x] Set up Story book
- [x] Install Vanilla extract
- [x] Set up Testing library
